# Generated by Django 3.1.4 on 2021-03-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
