# Generated by Django 3.1.4 on 2021-03-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_closing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('account_code', models.CharField(choices=[('T&T', 'T&T'), ('Salaries', 'Salaries'), ('Bills', 'Bills')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('account_code', models.CharField(choices=[('Orders', 'Orders'), ('Sales', 'Sales')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('orderno', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
