# Generated by Django 3.1.4 on 2021-04-03 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('shop', '0003_expenditure_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='account_code',
            field=models.CharField(choices=[('Orders', 'Orders'), ('Sales', 'Sales')], default='Sales', max_length=10),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
